[package]
name = "polars_business"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "polars_business"
crate-type = ["cdylib"]

[dependencies]
ahash = "0.8.3"
polars = { workspace = true, features = ["fmt", "dtype-date"], default-features = false }
polars-time = { workspace = true, default-features = false }
polars-plan = { workspace = true, default-features = false }
polars-ops = { workspace = true, default-features = false }
pyo3 = { version = "0.20.0", features = ["extension-module"] }
pyo3-polars = { git = "https://github.com/pola-rs/pyo3-polars", rev = "0a3df66ce626504e418491cb4b1d31bd3ee7ed6c", features = ["derive"] }
serde = { version = "1", features = ["derive"] }

[target .'cfg(target_os = "linux")']
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }
